
export const USER_CREATE_POST = "USER_CREATE_POST";
export const USER_AUTHENTICATE_POST = "USER_AUTHENTICATE_POST";

export const USER_DETAIL_GET_DETAILS = "USER_DETAIL_GET_DETAILS";
export const USER_DETAIL_GET_DETAIL = "USER_DETAIL_GET_DETAIL";
export const USER_DETAIL_CREATE_POST = "USER_DETAIL_CREATE_POST";
export const USER_DETAIL_UPDATE_POST = "USER_DETAIL_UPDATE_POST";


export const LEAVE_GET_DETAIL = "LEAVE_GET_DETAIL";
export const USER_LEAVE_GET_DETAILS = "USER_LEAVE_GET_DETAILS";
export const USER_LEAVE_CREATE_POST = "USER_LEAVE_CREATE_POST";
export const MANAGER_LEAVE_GET_DETAILS = "MANAGER_LEAVE_GET_DETAILS";
export const USER_LEAVE_UPDATE_POST = "USER_LEAVE_UPDATE_POST";

