# @format

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: notify-service
    name: notify-service
spec:
    replicas: 4
    selector:
        matchLabels:
            app: notify-service
    template:
        metadata:
            labels:
                app: notify-service
        spec:
            containers:
                - name: notify-service
                  image: 832215930943.dkr.ecr.us-east-1.amazonaws.com/notify-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8085
                        name: http
                        protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: notify-service
        k8s-app: notify-service
    name: notify-service
spec:
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8085
    type: LoadBalancer
    selector:
        app: notify-service
