import { AddressInterface } from "../../ui/forms/AddressForm";

export interface ItemMiniDTO {
  itemId?: number;
  itemIdFk: number;
  itemQuantity: number;
  price: number;
}

export interface ProductMiniDTO {
  productId?: number;
  productIdFk: number;
  quantity: number;
  price: number;
}

export interface CartSliceType {
  items: ItemMiniDTO[];
  selected: number[],
  totalAmount: number,
  totalItem: number,
}


export interface ItemDetailDTO {
  expiryDate: Date;
  itemId: number;
  itemQuantity: number;
  manufacturedDate: string;
  price: number;
  product: ProductDTO;
  store: Store;
}

export interface ProductDTO {
  categorySet: CategorySet[];
  description: string;
  dosageForm: string;
  imageUrl: string;
  productId: number;
  productName: string;
  productType: boolean;
  proprietaryName: string;
  quantity: number;
}

export interface CategorySet {
  categoryId: number;
  categoryName: string;
}

export interface Store {
  address: AddressInterface;
  createdDate: string;
  manager: Manager;
  revenue: number;
  storeId: number;
  storeName: string;
}

export interface Manager {
  approvalStatus: string;
  licenseNo: string;
  managerId: number;
  name: string;
  phoneNo: string;
  registrationDate: string;
}

export interface ProductDetailDTO {
  description: string;
  dosageForm: string;
  id: string;
  imageUrl: string;
  itemId: number;
  price: number;
  productId: number;
  productName: string;
  productType: boolean;
  proprietaryName: string;
  quantity: number;
  storeId: number;
}

// Generated by https://quicktype.io


export interface PrescriptionItem {
  id: number;
  name: string;
  quantity: number;
  price: number;
}