# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 832215930943.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
    k8s-app: order-service
  name: order-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  type: LoadBalancer
  selector:
    app: order-service
